eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 2222
spring:
    application:
        name: user-service
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: 19952017,Lzm
        url: jdbc:mysql://47.99.244.204:3306/db_account?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
        username: root
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        show-sql: true
    cloud:
        alibaba:
            seata:
                tx-service-group:  ${spring.application.name}-fescar-service-group