-- 0710
CREATE TABLE `t_user_update3` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` varchar(100) DEFAULT NULL COMMENT '姓名',
  `sex` varchar(10) DEFAULT NULL COMMENT '性别',
  `unit_id` varchar(20) DEFAULT NULL COMMENT '所在单位',
  `mobile` varchar(20) DEFAULT NULL COMMENT '手机号',
  `idcard` varchar(20) DEFAULT NULL COMMENT '身份证',
  `duty_str` varchar(255) DEFAULT NULL COMMENT '行政职务',
  `station_name` varchar(100) DEFAULT NULL COMMENT 'cs-关键岗位名称一',
  `project_scale` varchar(100) DEFAULT NULL COMMENT '大型,中型,小型项目',
  `station_name2` varchar(100) DEFAULT NULL COMMENT 'cs-关键岗位名称二',
  `project_scale2` varchar(100) DEFAULT NULL COMMENT '大型,中型,小型项目',
  `major` varchar(255) DEFAULT NULL COMMENT '从事专业',
  `is_civil` varchar(255) DEFAULT NULL COMMENT '是否能从事土建专业管理',
  `employment_form` varchar(200) DEFAULT NULL COMMENT '用工形式',
  `year_work` varchar(255) DEFAULT NULL COMMENT '岗位年限',
  `code_project_manager` varchar(255) DEFAULT NULL COMMENT '项目经理资质证编号',
--   `grade_project_manager` varchar(255) DEFAULT NULL COMMENT '项目经理资质证等级',
  `code_title` varchar(255) DEFAULT NULL COMMENT '职称等级',
  `grade_title` varchar(255) DEFAULT NULL COMMENT '职称编号',
  `grade_constructor` varchar(255) DEFAULT NULL COMMENT '建造师等级',
  `code_constructor` varchar(255) DEFAULT NULL COMMENT '建造师注册号',
  `major_constructor` varchar(255) DEFAULT NULL COMMENT '建造师专业',
  `grade_safety` varchar(255) DEFAULT NULL COMMENT '安全生产考核证等级',
  `code_safety` varchar(255) DEFAULT NULL COMMENT '安全生产考核证编号',
  `grade_safety_country` varchar(255) DEFAULT NULL COMMENT '国网公司或省公司安全培训合格证',
  `grade_skill` varchar(255) DEFAULT NULL COMMENT '技能等级',
  `code_skill` varchar(255) DEFAULT NULL COMMENT '技能等级编号',
  `name_quality` varchar(255) DEFAULT NULL COMMENT '质量培训合格证书名称',
  `code_quality` varchar(255) DEFAULT NULL COMMENT '质量培训合格证书编号',
  `reverse1` varchar(255) DEFAULT NULL COMMENT '预留字段',
  `reverse2` varchar(255) DEFAULT NULL COMMENT '预留字段',
  `reverse3` varchar(255) DEFAULT NULL COMMENT '预留字段',
  `reverse4` varchar(255) DEFAULT NULL COMMENT '预留字段',
  `user_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `id` (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COMMENT='送变电人员更新';

DROP TABLE IF EXISTS `t_user_history`;
CREATE TABLE `t_user_history` (
  `id` bigint(20) NOT NULL COMMENT '编号id',
  `user_id` bigint(20) DEFAULT NULL COMMENT '人员id',
  `update_id` bigint(20) DEFAULT NULL COMMENT '更新对应那次修改的某种类型id-暂时不用',
  `unit_id` bigint(20) DEFAULT NULL COMMENT '所在单位id',
  `unit_name` varchar(100) DEFAULT NULL COMMENT '所在单位名称',
  `depart_id` bigint(20) DEFAULT NULL COMMENT '部门ID',
  `username` varchar(50) DEFAULT NULL COMMENT '登录名',
  `password` varchar(500) DEFAULT NULL COMMENT '密码',
  `real_name` varchar(100) DEFAULT NULL COMMENT '姓名',
  `sex` varchar(10) DEFAULT NULL COMMENT '性别',
  `email` varchar(200) DEFAULT NULL COMMENT '邮箱',
  `mobile` varchar(20) DEFAULT NULL COMMENT '手机号',
  `idcard` varchar(20) DEFAULT NULL COMMENT '身份证证号',
  `native_place` varchar(255) DEFAULT NULL COMMENT '籍贯',
  `nation` varchar(40) DEFAULT NULL COMMENT '民族',
  `education_degree` varchar(32) DEFAULT NULL COMMENT '文化程度:doctor博士及以上;postgrad研究生；undergraduate本科；junior_college大专；polytechnic_school中专；hight高中；other其他；',
  `politic_countenance` varchar(50) DEFAULT NULL COMMENT '政治面貌：party党员；league团员；public群众；',
  `province` varchar(255) DEFAULT NULL COMMENT '省份',
  `address` varchar(255) DEFAULT NULL COMMENT '住址',
  `talent_level` varchar(50) DEFAULT NULL COMMENT '人才级别',
  `user_type` varchar(30) DEFAULT NULL COMMENT '用户类型(js.设计人员 ps.评审人员 sg.施工人员 xm.项目人员 jl.监理人员',
  `user_from` varchar(255) DEFAULT NULL COMMENT '用户来源',
  `app_lock_password` varchar(255) DEFAULT NULL COMMENT 'app锁屏密码',
  `is_reset_password` int(1) DEFAULT null COMMENT '是否重置过密码',
  `social_security_number` varchar(100) DEFAULT NULL COMMENT '社会保险号',
  `emg_contact_name` varchar(40) DEFAULT NULL COMMENT '紧急联系人姓名 ',
  `emg_contact_tel` varchar(40) DEFAULT NULL COMMENT '紧急联系人电话',
  `relation_ship` varchar(40) DEFAULT NULL COMMENT '和本人关系',
  `status` int(2) DEFAULT null COMMENT '状态：0未提交；10待审批；20待复核；30已完成',
  `update_status` int(2) DEFAULT NULL COMMENT '人员信息更新截止状态 1:基本信息,2:拓展信息,3:资质信息,4:人员附件',
  `confirm_status` int(4) DEFAULT null COMMENT '单位认定状态；0未通过认定；1已通过认定',
  `major_code` varchar(20) DEFAULT NULL COMMENT '从事专业code',
  `major_name` varchar(50) DEFAULT NULL COMMENT '从事专业名称',
  `major_time` datetime DEFAULT NULL COMMENT '从事专业时间',
  `work_time` datetime DEFAULT NULL COMMENT '从事工作时间',
  `duty_code` varchar(50) DEFAULT NULL COMMENT '岗位编码',
  `duty_name` varchar(50) DEFAULT NULL COMMENT '岗位名称',
  `employment_form` varchar(200) DEFAULT NULL COMMENT '用工形式',
  `main_station` varchar(100) DEFAULT NULL COMMENT 'cs-主要岗位',
  `minor_station` varchar(100) DEFAULT NULL COMMENT 'cs-次要岗位',
  `main_project_scale` varchar(255) DEFAULT NULL COMMENT 'cs-施工可承揽大工程规模',
  `minor_project_scale` varchar(255) DEFAULT NULL COMMENT 'cs-施工可承揽小工程规模',
  `duty_administration` varchar(20) DEFAULT NULL COMMENT 'cs-行政职务',
  `is_committee` int(2) DEFAULT null COMMENT 'cs-是否启委会成员（0不是，1是，默认0）',
  `is_on_site` varchar(2) DEFAULT null COMMENT 'cs-是否现场人员 0 否 1是',
  `sb_project_count` int(11) DEFAULT null COMMENT 'cs-参与变电工程现场作业时间工程数',
  `sb_project_correction` int(125) DEFAULT null COMMENT 'cs-参与变电工程现场作业时间工程数 修正值',
  `monitor_sb_project` int(11) DEFAULT null COMMENT 'cs-担任班长的输变电工程数量',
  `monitor_sb_correction` int(125) DEFAULT null COMMENT 'cs-担任班长的输变电工程数量修正值',
  `sb_start_time` datetime DEFAULT NULL COMMENT 'cs-从事输变电工程施工的开始时间',
  `sb_year` int(11) DEFAULT NULL COMMENT 'cs-从事输变电工程施工的工作年限',
  `job_performance` varchar(255) DEFAULT NULL COMMENT 'cs-工作业绩',
  `remarks` varchar(255) DEFAULT NULL COMMENT 'cs-备注',
  `creater_id` bigint(20) DEFAULT NULL COMMENT '创建者',
  `create_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` bigint(20) DEFAULT NULL COMMENT '更新者',
  `modify_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `is_deleted` int(1) NOT NULL DEFAULT null COMMENT '删除标记',
  `is_unit_admin` int(1) DEFAULT null COMMENT '0为普通人员,1位单位管理员',
  `is_leader_charge` int(1) DEFAULT null COMMENT '是否分管领导;0否1是',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户历史表';



CREATE TABLE `user_exam` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `kaochang` varchar(100) DEFAULT NULL COMMENT '类型1',
  `unit` varchar(100) DEFAULT NULL COMMENT '类型2',
  `num` varchar(100) DEFAULT NULL COMMENT '类型2',
  `name` varchar(100) DEFAULT NULL COMMENT '预留1',
  `idcard` varchar(100) DEFAULT NULL COMMENT '预留2',
  `major` varchar(100) DEFAULT NULL COMMENT '预留2',
  `user_type` varchar(100) DEFAULT NULL COMMENT '预留2',
  `exam_major` varchar(100) DEFAULT NULL COMMENT '预留2',
  `is_pass` varchar(100) DEFAULT NULL COMMENT '预留2',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=358 DEFAULT CHARSET=utf8mb4 COMMENT='字段数据一对多的关系';





