package com.example.xademo.dblocalhost.dao;

import com.example.xademo.dblocalhost.model.XALocalhost;
import com.example.xademo.dblocalhost.model.XALocalhostExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface XALocalhostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_132
     *
     * @mbg.generated Wed Oct 02 17:02:36 CST 2019
     */
    long countByExample(XALocalhostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_132
     *
     * @mbg.generated Wed Oct 02 17:02:36 CST 2019
     */
    int deleteByExample(XALocalhostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_132
     *
     * @mbg.generated Wed Oct 02 17:02:36 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_132
     *
     * @mbg.generated Wed Oct 02 17:02:36 CST 2019
     */
    int insert(XALocalhost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_132
     *
     * @mbg.generated Wed Oct 02 17:02:36 CST 2019
     */
    int insertSelective(XALocalhost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_132
     *
     * @mbg.generated Wed Oct 02 17:02:36 CST 2019
     */
    List<XALocalhost> selectByExample(XALocalhostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_132
     *
     * @mbg.generated Wed Oct 02 17:02:36 CST 2019
     */
    XALocalhost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_132
     *
     * @mbg.generated Wed Oct 02 17:02:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") XALocalhost record, @Param("example") XALocalhostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_132
     *
     * @mbg.generated Wed Oct 02 17:02:36 CST 2019
     */
    int updateByExample(@Param("record") XALocalhost record, @Param("example") XALocalhostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_132
     *
     * @mbg.generated Wed Oct 02 17:02:36 CST 2019
     */
    int updateByPrimaryKeySelective(XALocalhost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_132
     *
     * @mbg.generated Wed Oct 02 17:02:36 CST 2019
     */
    int updateByPrimaryKey(XALocalhost record);
}