eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:1111/eureka/
rocketmq:
    name-server: 127.0.0.1:9876
    producer:
        group: producer_bank2
server:
    port: 2223
spring:
    application:
        name: user-service1
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: 19952017,Lzm
        url: jdbc:mysql://47.99.244.204:3306/db_account?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
        username: root
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        show-sql: true
